[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parallel_models"
version = "0.1.0"
authors = [
    {name="Name", email="name@gmail.com"}
]
description = "Parallelizable Transformers"
readme = ""
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
license = { "text" = "MIT" }
dependencies = [
    "accelerate>=0.26.0",
    "datasets>=2.16.0",
    "peft>=0.2.0",
    "scikit-learn>=0.24.1",
    "torch>=1.8",
    "transformers>=4.1",
    "more_itertools",
]

[tool.setuptools.packages.find]
include = ["parallel_models*"]

# required to include yaml files in pip installation
# [tool.setuptools.package-data]
# lm_eval = ["**/*.yaml", "tasks/**/*"]

# [project.scripts]
# lm-eval = "lm_eval.__main__:cli_evaluate"
# lm_eval = "lm_eval.__main__:cli_evaluate"


